### ISSUE TITLE
[installing with pip] Could not find any downloads that satisfy the requirement yaml

### ISSUE THREAD

**Issue by bengolder** [waylan/docdata#1]
First of all, thank you for splitting this off from the markdown repo and creating this package. I think it's quite useful to have this as a separate piece of functionality.

Was trying to install with pip, using the following line in a `requirements.txt` file:

```
http://github.com/waylan/docdata/archive/master.zip
```

And received this error

```
Downloading/unpacking yaml (from docdata==0.0.1->-r requirements.txt (line 3))
  Real name of requirement yaml is yaml
  Could not find any downloads that satisfy the requirement yaml (from docdata==0.0.1->-r requirements.txt (line 3))
Cleaning up...
No distributions at all found for yaml (from docdata==0.0.1->-r requirements.txt (line 3))
```

In `setup.py`, should

```
install_requires = ['yaml'],
```

be 

```
install_requires = ['pyyaml'],
```

?

Or am I installing it incorrectly?

**Comment by waylan** [comment]
Yes, you are correct. Because we do `import yaml` I always forget the lib is named "pyyaml" in PyPI.
