### ISSUE TITLE
ImportError: No module named pychart

### ISSUE THREAD

**Issue by Jmvc2406** [waylan/docdata#2]
hi good morning any idea what file to download

odio 10, MacOx, install

**Comment by waylan** [comment]
pychart is not something used (or imported) by this library. Additionaly, I have no idea what "odio" is. Either I'm misunderstanding your problem to you'll need to ask someone else knowledgeable about what you are tying to do.

**Comment by Jmvc2406** [comment]
i want to install it to run odoo 10 and i can not find the library, maybe it can be downloaded from another library for MacOx

**Comment by waylan** [comment]
I don't know what odio is and I don't use anything called pychart. You need to ask someone else. If someone else has used docdata and somehow incorporated pychart into it, then you need to ask that person.

**Comment by Jmvc2406** [comment]
This is what i did:
jmvc:odoo jmvc2406$ ./odoo-bin --adoons-path=addons
  File "/Users/jmvc2406/odoo/odoo/odoo/report/custom.py", line 9, in <module>
    from pychart import area, arrow, axis, bar_plot, canvas, category_coord, \
ImportError: No module named pychart

What of "odio" was typing error sorry

**Comment by waylan** [comment]
Then you need to ask the people who develop odoo. I have no idea that that is or what "pychart" lib they may be using. I don't understand why you are asking here.
